name: Deploy AWS Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Validate Terraform configuration
        working-directory: /home/runner/work/terraform-aws-lambda/terraform
        run: |
          terraform init
          terraform validate

      - name: Zip Python code
        run: |
          zip -r lambda.zip lambda_function.py

      - name: Initialize and apply Terraform
        working-directory: /home/runner/work/terraform-aws-lambda/terraform
        run: |
          terraform init
          terraform apply -auto-approve -var "aws_region=$AWS_DEFAULT_REGION" -var "lambda_filename=lambda.zip" -var "aws_access_key_id=$AWS_ACCESS_KEY_ID" -var "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY"